use std::path::PathBuf;
use std::process::Command;

use tauri::AppHandle;

use crate::audio::pw_enum::nodes_by_class;

use super::{VirtualDeviceConfig, VirtualDriverStatus};

const CONF_NAME: &str = "50-splitwave-sinks.conf";
const NODE_PREFIX: &str = "splitwave";

fn conf_path() -> Option<PathBuf> {
    Some(dirs::config_dir()?.join("pipewire/pipewire.conf.d").join(CONF_NAME))
}

// node.name is the stable handle, node.description is the label shown in
// system settings. Quotes would break both the .conf and the pw-cli props, so
// drop them from the label.
fn clean_label(name: &str) -> String {
    name.replace(['"', '\''], "")
}

// PipeWire channel map. Standard names for mono/stereo; generic AUX for wider
// layouts so any channel count is accepted.
fn positions(channels: u32) -> String {
    let list: Vec<String> = match channels.clamp(1, 64) {
        1 => vec!["MONO".into()],
        2 => vec!["FL".into(), "FR".into()],
        n => (0..n).map(|i| format!("AUX{i}")).collect(),
    };
    list.join(" ")
}

pub fn status() -> VirtualDriverStatus {
    // Native PipeWire (no PulseAudio/pactl dependency). Success means a session
    // is reachable, which is all we need to create null-sinks.
    let ok = Command::new("pw-cli")
        .args(["info", "0"])
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false);
    VirtualDriverStatus {
        installed: ok,
        installed_version: None,
        current_version: super::DRIVER_VERSION,
        needs_update: false,
    }
}

pub fn install(_app: &AppHandle) -> Result<(), String> {
    // No driver to install on PipeWire; sinks are created directly.
    Ok(())
}

pub fn uninstall() -> Result<(), String> {
    unload_runtime_sinks();
    if let Some(p) = conf_path() {
        let _ = std::fs::remove_file(p);
    }
    Ok(())
}

pub fn apply_virtual_devices(devices: Vec<VirtualDeviceConfig>) -> Result<(), String> {
    unload_runtime_sinks();

    let conf = conf_path().ok_or("no config directory")?;
    if devices.is_empty() {
        let _ = std::fs::remove_file(&conf);
        return Ok(());
    }

    if let Some(parent) = conf.parent() {
        std::fs::create_dir_all(parent).map_err(|e| format!("create conf dir: {e}"))?;
    }
    std::fs::write(&conf, conf_contents(&devices)).map_err(|e| format!("write conf: {e}"))?;

    for d in &devices {
        create_runtime_sink(&d.id, &clean_label(&d.name), d.channels)?;
    }
    Ok(())
}

fn conf_contents(devices: &[VirtualDeviceConfig]) -> String {
    let mut out = String::from("# Auto-generated by Splitwave. Do not edit.\n\ncontext.objects = [\n");
    for d in devices {
        let desc = clean_label(&d.name);
        out.push_str("  {\n");
        out.push_str("    factory = adapter\n");
        out.push_str("    args = {\n");
        out.push_str("      factory.name     = support.null-audio-sink\n");
        out.push_str(&format!("      node.name        = \"{NODE_PREFIX}.{}\"\n", d.id));
        out.push_str(&format!("      node.description = \"{desc}\"\n"));
        out.push_str("      media.class      = Audio/Sink\n");
        out.push_str(&format!("      audio.position   = [ {} ]\n", positions(d.channels)));
        out.push_str("      object.linger    = true\n");
        out.push_str("    }\n");
        out.push_str("  }\n");
    }
    out.push_str("]\n");
    out
}

// Create the sink in the running session so it shows up immediately. The .conf
// only takes effect on the next PipeWire start; object.linger keeps the node
// alive after pw-cli disconnects.
fn create_runtime_sink(id: &str, label: &str, channels: u32) -> Result<(), String> {
    let props = format!(
        "{{ factory.name=support.null-audio-sink node.name={NODE_PREFIX}.{id} node.description=\"{label}\" media.class=Audio/Sink audio.position=[ {} ] object.linger=true }}",
        positions(channels)
    );
    let out = Command::new("pw-cli")
        .args(["create-node", "adapter", props.as_str()])
        .output()
        .map_err(|e| format!("pw-cli create-node: {e}"))?;
    if !out.status.success() {
        return Err(format!(
            "pw-cli create-node failed: {}",
            String::from_utf8_lossy(&out.stderr).trim()
        ));
    }
    Ok(())
}

fn unload_runtime_sinks() {
    let prefix = format!("{NODE_PREFIX}.");
    let Ok(nodes) = nodes_by_class("Audio/Sink") else {
        return;
    };
    for n in nodes {
        if n.name.starts_with(&prefix) {
            let id = n.id.to_string();
            let _ = Command::new("pw-cli").args(["destroy", id.as_str()]).status();
        }
    }
}
