use std::path::PathBuf;

use pipewire as pw;
use tauri::AppHandle;

use crate::audio::pw_enum::nodes_by_class;

use super::{VirtualDeviceConfig, VirtualDriverStatus};

const CONF_NAME: &str = "50-splitwave-sinks.conf";
const NODE_PREFIX: &str = "splitwave";

fn conf_path() -> Option<PathBuf> {
    Some(
        dirs::config_dir()?
            .join("pipewire/pipewire.conf.d")
            .join(CONF_NAME),
    )
}

// node.name is the stable handle, node.description is the label shown in
// system settings. Quotes would break both the .conf and the created node
// props, so drop them from the label.
fn clean_label(name: &str) -> String {
    name.replace(['"', '\''], "")
}

// PipeWire channel map. Standard names for mono/stereo; generic AUX for wider
// layouts so any channel count is accepted.
fn positions(channels: u32) -> String {
    let list: Vec<String> = match channels.clamp(1, 256) {
        1 => vec!["MONO".into()],
        2 => vec!["FL".into(), "FR".into()],
        n => (0..n).map(|i| format!("AUX{i}")).collect(),
    };
    list.join(" ")
}

pub fn status() -> VirtualDriverStatus {
    // Native PipeWire (no subprocess): a reachable session is all we need to
    // create null-sinks.
    let ok = nodes_by_class("Audio/Sink").is_ok();
    VirtualDriverStatus {
        installed: ok,
        installed_version: None,
        current_version: super::DRIVER_VERSION,
        needs_update: false,
    }
}

pub fn install(_app: &AppHandle) -> Result<(), String> {
    // No driver to install on PipeWire; sinks are created directly.
    Ok(())
}

pub fn uninstall() -> Result<(), String> {
    unload_runtime_sinks();
    if let Some(p) = conf_path() {
        let _ = std::fs::remove_file(p);
    }
    Ok(())
}

pub fn apply_virtual_devices(devices: Vec<VirtualDeviceConfig>) -> Result<(), String> {
    unload_runtime_sinks();

    let conf = conf_path().ok_or("no config directory")?;
    if devices.is_empty() {
        let _ = std::fs::remove_file(&conf);
        return Ok(());
    }

    if let Some(parent) = conf.parent() {
        std::fs::create_dir_all(parent).map_err(|e| format!("create conf dir: {e}"))?;
    }
    std::fs::write(&conf, conf_contents(&devices)).map_err(|e| format!("write conf: {e}"))?;

    for d in &devices {
        create_runtime_sink(&d.id, &clean_label(&d.name), d.channels)?;
    }
    Ok(())
}

fn conf_contents(devices: &[VirtualDeviceConfig]) -> String {
    let mut out =
        String::from("# Auto-generated by Splitwave. Do not edit.\n\ncontext.objects = [\n");
    for d in devices {
        let desc = clean_label(&d.name);
        out.push_str("  {\n");
        out.push_str("    factory = adapter\n");
        out.push_str("    args = {\n");
        out.push_str("      factory.name     = support.null-audio-sink\n");
        out.push_str(&format!(
            "      node.name        = \"{NODE_PREFIX}.{}\"\n",
            d.id
        ));
        out.push_str(&format!("      node.description = \"{desc}\"\n"));
        out.push_str("      media.class      = Audio/Sink\n");
        out.push_str(&format!(
            "      audio.position   = [ {} ]\n",
            positions(d.channels)
        ));
        out.push_str("      object.linger    = true\n");
        out.push_str("    }\n");
        out.push_str("  }\n");
    }
    out.push_str("]\n");
    out
}

// Connect a short-lived PipeWire session, apply `f`, and wait one round-trip so
// the server-side change is registered before we disconnect.
fn with_session(
    f: impl FnOnce(&pw::core::CoreRc, &pw::main_loop::MainLoopRc) -> Result<(), String>,
) -> Result<(), String> {
    pw::init();
    let mainloop =
        pw::main_loop::MainLoopRc::new(None).map_err(|e| format!("pipewire mainloop: {e}"))?;
    let context = pw::context::ContextRc::new(&mainloop, None)
        .map_err(|e| format!("pipewire context: {e}"))?;
    let core = context
        .connect_rc(None)
        .map_err(|e| format!("pipewire connect: {e}"))?;
    let res = f(&core, &mainloop);
    mainloop.quit();
    res
}

fn roundtrip(core: &pw::core::CoreRc, mainloop: &pw::main_loop::MainLoopRc) -> Result<(), String> {
    let pending = core.sync(0).map_err(|e| format!("pipewire sync: {e}"))?;
    let ml = mainloop.clone();
    let _l = core
        .add_listener_local()
        .done(move |id, seq| {
            if id == 0 && seq == pending {
                ml.quit();
            }
        })
        .register();
    mainloop.run();
    Ok(())
}

// Create the sink in the running session so it shows up immediately. The .conf
// only takes effect on the next PipeWire start; object.linger keeps the node
// alive after we disconnect.
fn create_runtime_sink(id: &str, label: &str, channels: u32) -> Result<(), String> {
    with_session(|core, mainloop| {
        let mut props = pw::properties::properties! {
            *pw::keys::FACTORY_NAME => "support.null-audio-sink",
            *pw::keys::MEDIA_CLASS => "Audio/Sink",
            "object.linger" => "1",
        };
        props.insert(*pw::keys::NODE_NAME, format!("{NODE_PREFIX}.{id}"));
        props.insert(*pw::keys::NODE_DESCRIPTION, label.to_string());
        props.insert("audio.position", positions(channels));
        let _node: pw::node::Node = core
            .create_object("adapter", &props)
            .map_err(|e| format!("create null sink: {e}"))?;
        roundtrip(core, mainloop)
    })
}

fn unload_runtime_sinks() {
    let prefix = format!("{NODE_PREFIX}.");
    let Ok(nodes) = nodes_by_class("Audio/Sink") else {
        return;
    };
    let mine: Vec<u32> = nodes
        .iter()
        .filter(|n| n.name.starts_with(&prefix))
        .map(|n| n.id)
        .collect();
    if mine.is_empty() {
        return;
    }
    let _ = with_session(|core, mainloop| {
        let registry = core
            .get_registry()
            .map_err(|e| format!("pipewire registry: {e}"))?;
        for id in mine {
            registry
                .destroy_global(id)
                .into_result()
                .map_err(|e| format!("destroy sink {id}: {e:?}"))?;
        }
        roundtrip(core, mainloop)
    });
}
